
[mcp_servers.serena]
type = "streamableHttp"
url = "http://localhost:9121/mcp"
[mcp_servers.context7]
command = "pnpm"
args = ["dlx", "@upstash/context7-mcp"]

[mcp_servers.shadcn]
command = "pnpm"
args = ["dlx", "shadcn-vue@latest", "mcp"]

[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]