[program:nova-helpdesk-reverb]
process_name=%(program_name)s
directory=/srv/nova-helpdesk/current
command=/usr/bin/php artisan reverb:start
user=deployer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nova-helpdesk-reverb.log
stopwaitsecs=60

[program:nova-helpdesk-queue]
process_name=%(program_name)s_%(process_num)02d
directory=/srv/nova-helpdesk/current
command=/usr/bin/php artisan queue:work --sleep=3 --tries=3 --max-time=3600
user=deployer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/nova-helpdesk-queue.log
stopwaitsecs=60
